# Generated by Django 2.1.7 on 2019-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Event title ')),
                ('venue', models.CharField(max_length=255, verbose_name='Venue ')),
                ('date', models.DateTimeField(verbose_name='Event date ')),
                ('description', models.TextField(verbose_name='Event Description ')),
                ('image', models.ImageField(upload_to='events/images/', verbose_name='Event image ')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
