# Generated by Django 2.1.7 on 2019-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image name ')),
                ('image', models.ImageField(upload_to='gallery/images')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video name ')),
                ('video', models.URLField(max_length=300, verbose_name='Video url ')),
            ],
            options={
                'verbose_name': 'Videos',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
